// ─── Mock Catalog Data ────────────────────────────────────────────────────────
window.mockCatalogData = [
  {
    id: "place_001",
    name: "Coliseo Romano",
    category: "tourist_attraction",
    categoryLabel: "Atracción Histórica",
    emoji: "🏛️",
    isVerified: true,
    price: "$$",
    priceLabel: "Precio moderado",
    rating: 4.8,
    reviews: 94210,
    tags: ["Ideal para familias", "Aventura", "Accesible"],
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=800&auto=format&fit=crop",
    description: "Anfiteatro icónico del Imperio Romano, sede de los gladiadores.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_002",
    name: "Trattoria da Enzo al 29",
    category: "restaurant",
    categoryLabel: "Restaurante Italiano",
    emoji: "🍽️",
    isVerified: false,
    price: "$$",
    priceLabel: "Precio moderado",
    rating: 4.6,
    reviews: 3842,
    tags: ["Ideal para familias", "Vida Nocturna"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=800&auto=format&fit=crop",
    description: "Joya oculta del Trastevere. Pasta fresca hecha a mano, ambiente íntimo.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_003",
    name: "Hotel de Russie",
    category: "lodging",
    categoryLabel: "Hotel · 5 Estrellas",
    emoji: "🏨",
    isVerified: true,
    price: "$$$",
    priceLabel: "Precio alto",
    rating: 4.9,
    reviews: 7651,
    tags: ["Accesible"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800&auto=format&fit=crop",
    description: "Hotel de lujo con jardines secretos a pasos de la Piazza del Popolo.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_004",
    name: "Mercado de Testaccio",
    category: "tourist_attraction",
    categoryLabel: "Mercado Local",
    emoji: "🛒",
    isVerified: false,
    price: "$",
    priceLabel: "Económico",
    rating: 4.4,
    reviews: 2190,
    tags: ["Ideal para familias", "Aventura"],
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?q=80&w=800&auto=format&fit=crop",
    description: "Mercado cubierto con puestos de productores locales, una experiencia auténtica.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_005",
    name: "Termini · Metro & Treni",
    category: "transit_station",
    categoryLabel: "Estación Central",
    emoji: "🚊",
    isVerified: true,
    price: "free",
    priceLabel: "Gratis",
    rating: 3.9,
    reviews: 55300,
    tags: ["Accesible"],
    image: "https://images.unsplash.com/photo-1541430486573-0c8b9f9a5a8d?q=80&w=800&auto=format&fit=crop",
    description: "El hub de transporte más grande de Roma, conecta metro, buses y trenes.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_006",
    name: "Generator Rome Hostel",
    category: "lodging",
    categoryLabel: "Hostel Boutique",
    emoji: "🏠",
    isVerified: true,
    price: "$",
    priceLabel: "Económico",
    rating: 4.3,
    reviews: 9870,
    tags: ["Vida Nocturna", "Aventura"],
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?q=80&w=800&auto=format&fit=crop",
    description: "Hostel design premiado, bar en la azotea con vistas panorámicas a la ciudad.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_007",
    name: "Osteria dell'Enoteca",
    category: "restaurant",
    categoryLabel: "Bar de Vinos",
    emoji: "🍷",
    isVerified: false,
    price: "$$$",
    priceLabel: "Precio alto",
    rating: 4.7,
    reviews: 1230,
    tags: ["Vida Nocturna"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=800&auto=format&fit=crop",
    description: "Enoteca íntima con selección de más de 400 vinos italianos y tabla de quesos.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_008",
    name: "Parque del Appia Antica",
    category: "tourist_attraction",
    categoryLabel: "Parque Natural",
    emoji: "🌿",
    isVerified: true,
    price: "free",
    priceLabel: "Gratis",
    rating: 4.7,
    reviews: 18540,
    tags: ["Ideal para familias", "Aventura", "Accesible"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop",
    description: "Un oasis verde en la ciudad, hogar de ruinas antiguas y ciclismo al aire libre.",
    city: "Roma",
    country: "Italia"
  },
  {
    id: "place_009",
    name: "Atac Bus Nocturno · N1/N2",
    category: "transit_station",
    categoryLabel: "Transporte Nocturno",
    emoji: "🚌",
    isVerified: false,
    price: "$",
    priceLabel: "Económico",
    rating: 3.5,
    reviews: 4420,
    tags: ["Vida Nocturna"],
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=800&auto=format&fit=crop",
    description: "Red de buses nocturnos que conecta los barrios más animados de Roma.",
    city: "Roma",
    country: "Italia"
  }
];
